### ISSUE TITLE
Night Light occasionally does not work

### ISSUE THREAD

**Issue by thomorl** [elementary/wingpanel-indicator-nightlight#47] opened 2019-05-07 09:15 UTC
Sometimes, Night Light does not start at the displayed/configured time, no matter if it's in `Sunset to Sunrise` or `Manual` mode. Using the Night Light switch in Settings does not work in these cases, only rebooting fixes the problem.

**Comment by peteruithoven** [comment] 2019-05-07 09:44
I think the indicator talks to the `gsd-color` process. 
If it doesn't work is this process listed in `htop`?
Have you tried restarting it?
```
killall gsd-color
``

You could think of the nightlight indicator being just an interface for a gnome color daemon: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/tree/master/plugins/color

**Comment by ashadnasim52** [comment] 2019-05-28 18:17
> Sometimes, Night Light does not start at the displayed/configured time, no matter if it's in `Sunset to Sunrise` or `Manual` mode. Using the Night Light switch in Settings does not work in these cases, only rebooting fixes the problem.
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/73817656-night-light-occasionally-does-not-work?utm_campaign=plugin&utm_content=tracker%2F81352626&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F81352626&utm_medium=issues&utm_source=github).

yeah I had feel too

**Comment by ashadnasim52** [comment] 2019-05-28 18:27
> Sometimes, Night Light does not start at the displayed/configured time, no matter if it's in `Sunset to Sunrise` or `Manual` mode. Using the Night Light switch in Settings does not work in these cases, only rebooting fixes the problem.
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/73817656-night-light-occasionally-does-not-work?utm_campaign=plugin&utm_content=tracker%2F81352626&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F81352626&utm_medium=issues&utm_source=github).

yeah I had feel too

**Comment by thomorl** [comment] 2019-06-27 09:21
> I think the indicator talks to the `gsd-color` process.
> If it doesn't work is this process listed in `htop`?
> Have you tried restarting it?
> 
> ```
> killall gsd-color
> ```
> 
> You could think of the nightlight indicator being just an interface for a gnome color daemon: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/tree/master/plugins/color

This fixes the problem, thanks.

**Comment by thomorl** [comment] 2019-06-27 09:26
Thinking about less tech-savvy users, would there be a way for the Night Light indicator to detect such issues and automatically offer a solution, maybe in the form of a label/notification:
> Hey, Night Light seems to have run into an issue. Click 'Fix' to fix it.

Or even fix it automatically, on it's own. Entering a terminal command every time this problem occurrs is not really an elegant/efficient solution to the problem.

**Comment by peteruithoven** [comment] 2019-06-27 09:39
Yeah but adding these kind of daemon restart options could be applied to many many aspects of the OS... 
What about a way to easily restart Gala, bluetooth, the network stack, Wingpanel, Plank etc etc. 

I'd advice checking the issue queue for similar issues and if it's not listed try and figure out how to reproduce this issue. 

I'm closing this issue since it's not an issue with the indicator itself.

**Closed by peteruithoven** 2019-06-27 09:39 UTC

**Comment by 4jNsY6fCVqZv** [comment] 2019-11-16 17:13
@peteruithoven Since this issue still occurs frequently and does not seem explainable or solvable for less technical users, I ask you what a solution might look like? The fix described above works, but I can't imagine that this is the standard user behavior that you wish/imagine.
