### ISSUE TITLE
wake up of suspend the icon nightlight not appear 

### ISSUE THREAD

**Issue by torikulhabib** [elementary/wingpanel-indicator-nightlight#34] opened 2018-08-14 13:38 UTC
![screenshot from 2018-08-14 19-35-10](https://user-images.githubusercontent.com/26135527/44095056-04f5842c-a002-11e8-8a18-ebd4f11fcba7.png)

**Comment by peteruithoven** [comment] 2019-04-17 06:52
I can't reproduce. 
There is a change this was fixed with: https://github.com/elementary/wingpanel/pull/187
Are you still experiencing this issue?

**Closed** 2024-07-07 07:40 UTC
