### ISSUE TITLE
Night light should work at login screen when there's only one user or all users have the same settings

### ISSUE THREAD

**Issue by minhdanh** [elementary/wingpanel-indicator-nightlight#43] opened 2018-12-03 14:55 UTC
When Night light is turned on, on log in screen it doesn't work.
I think it should work even at login screen when there's only one user on the system (that has Night Light enabled) or all users have the same Night Light setings.

**Comment by jeremypw** [comment] 2018-12-03 16:06
The problem is, nightlight settings could differ between users ...

**Comment by minhdanh** [comment] 2018-12-04 02:01
This is my Night Light setting:

![image](https://user-images.githubusercontent.com/4865412/49413633-2490cf00-f7a3-11e8-9327-d8ae7f782076.png)

**Comment by jeremypw** [comment] 2018-12-04 13:41
I meant that there could be more than one user for the same system - with different nightlight settings.  Perhaps the login screen could honor the user setting if there is only one user (or if all users have the same setting)?

**Comment by minhdanh** [comment] 2018-12-04 14:09
Ah. I see.
> Perhaps the login screen could honor the user setting if there is only one user (or if all users have the same setting)?
I've just tried on my Mac and I can see the similar behavior like you said. Night shift is slowly disabled at login screen if I locked the Macbook and switched to login screen (after creating a new user that doesn't enable Night Shift).
Before when there was only one user (it's me), macOS respects my Night Shift settings.
I think that is better then just default to not enable Night Light at login screen.

**Comment by jeremypw** [comment] 2018-12-04 14:47
OK, in that case could you update the issue title and description to clarify that it only applies if there is only one user?

**Comment by grafst** [comment] 2019-04-25 20:30
I have an Idea: Why not adjust it to the selected user on the login screen?
The Wallpaper also gets adjusted depending on which user you select. This way, when locking the screen the nightlight stays at the same intensity unless another user is selected.

**Comment by fabiozaramella** [comment] 2020-10-26 04:08
This is a pretty old feature request indeed but i think it needs consideration, so I'm reopening it waiting for a response from @elementary/ux team. The plan is to store and honor other user-related settings like the accent color and so on and I think night light should be one of these (if technically feasible) because sometimes an user might want to use it's account after another one that doesn't use night light and it could be really annoying to end up having a very bright screen in a dark environment before going to bed.

**Comment by cassidyjames** [comment] 2020-10-27 18:33
I agree this would be good. I think @davidmhewitt would have thoughts? It should behave like the keyboard layout imho, where selecting the card switches to using that user's settings. 

I don't think it is worthwhile to try and check if all the settings are the same and only implement it then, as it's super easy to tweak the temperature to one users' liking which would make it out of sync.

**Comment by lenemter** [comment] 2023-06-23 07:58
I'll close this as duplicate of https://github.com/elementary/greeter/issues/288. The fix for this already exists, hope it'll be merged soon.

**Closed by lenemter** 2023-06-23 07:58 UTC
